server:
  port: 8086

spring:
  application:
    name: orchestrator-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chrono_db?currentSchema=chrono_orchestrator
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      pool-name: OrchestratorHikariPool
  jpa:
    properties:
      hibernate:
        default_schema: chrono_orchestrator
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chrono_orchestrator
    liquibase-schema: chrono_orchestrator

async:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: orchestrator-async-

logging:
  level:
    com.chrono.orchestrator: DEBUG
