server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chrono_db?currentSchema=chrono_user
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 30000
      pool-name: UserHikariPool
  jpa:
    properties:
      hibernate:
        default_schema: chrono_user
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chrono_user
    liquibase-schema: chrono_user
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 min

logging:
  level:
    com.chrono.user: DEBUG
